name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Transfer code to EC2
        run: |
          echo "$KNOWN_HOSTS" > known_hosts
          scp -o UserKnownHostsFile=known_hosts -r ./job ec2-user@3.83.149.214:/home/ec2-user


      - name: SSH into EC2 and deploy
        run: |
          ssh ec2-user@3.83.149.214 << 'EOF'
          sudo cp -r /home/ec2-user/job/* /var/www/html/
          sudo systemctl restart httpd
          EOF
